version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub-test
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  flaconiuserjourney:
    image: vikramkv15/vikramrepository:flaconiuserjourney
    container_name: flaconitestuserjourney
    depends_on:
      - chrome
    environment:
      - MODULE=FlaconiUserJourney.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - /home/user/flaconiuserjourney-result:/output